COUNTRY_NAME_EN_CN = {
    # Asia
    '中国': 'China',
    '日本': 'Japan',
    '韩国': 'South Korea',
    '印度': 'India',
    '泰国': 'Thailand',
    '越南': 'Vietnam',
    '马来西亚': 'Malaysia',
    '新加坡': 'Singapore',
    '菲律宾': 'Philippines',
    '印度尼西亚': 'Indonesia',
    '孟加拉国': 'Bangladesh',
    '巴基斯坦': 'Pakistan',
    '斯里兰卡': 'Sri Lanka',
    '尼泊尔': 'Nepal',
    '哈萨克斯坦': 'Kazakhstan',
    '乌兹别克斯坦': 'Uzbekistan',
    '伊朗': 'Iran',
    '伊拉克': 'Iraq',
    '以色列': 'Israel',
    '阿联酋': 'UAE',
    '沙特阿拉伯': 'Saudi Arabia',
    '卡塔尔': 'Qatar',
    '科威特': 'Kuwait',
    '土耳其': 'Turkey',

    # Europe
    '英国': 'UK',
    '法国': 'France',
    '德国': 'Germany',
    '意大利': 'Italy',
    '西班牙': 'Spain',
    '葡萄牙': 'Portugal',
    '荷兰': 'Netherlands',
    '比利时': 'Belgium',
    '瑞士': 'Switzerland',
    '奥地利': 'Austria',
    '挪威': 'Norway',
    '瑞典': 'Sweden',
    '丹麦': 'Denmark',
    '芬兰': 'Finland',
    '爱尔兰': 'Ireland',
    '波兰': 'Poland',
    '捷克': 'Czech Republic',
    '斯洛伐克': 'Slovakia',
    '匈牙利': 'Hungary',
    '希腊': 'Greece',
    '罗马尼亚': 'Romania',
    '保加利亚': 'Bulgaria',
    '俄罗斯': 'Russia',
    '乌克兰': 'Ukraine',
    '爱沙尼亚': 'Estonia',
    '拉脱维亚': 'Latvia',
    '立陶宛': 'Lithuania',

    # Americas
    '美国': 'USA',
    '加拿大': 'Canada',
    '墨西哥': 'Mexico',
    '巴西': 'Brazil',
    '阿根廷': 'Argentina',
    '智利': 'Chile',
    '哥伦比亚': 'Colombia',
    '秘鲁': 'Peru',
    '乌拉圭': 'Uruguay',
    '委内瑞拉': 'Venezuela',
    '古巴': 'Cuba',

    # Africa
    '南非': 'South Africa',
    '尼日利亚': 'Nigeria',
    '埃及': 'Egypt',
    '摩洛哥': 'Morocco',
    '肯尼亚': 'Kenya',
    '埃塞俄比亚': 'Ethiopia',
    '突尼斯': 'Tunisia',
    '加纳': 'Ghana',
    '阿尔及利亚': 'Algeria',
    '刚果民主共和国': 'Democratic Republic of the Congo',

    # Oceania
    '澳大利亚': 'Australia',
    '新西兰': 'New Zealand',
    '斐济': 'Fiji',
    '巴布亚新几内亚': 'Papua New Guinea',

    # Regions and Special Cases (optional)
    '香港': 'Hong Kong',
    '澳门': 'Macau',
    '台湾': 'Taiwan',
    '苏格兰': 'Scotland',
    '威尔士': 'Wales',
    '英格兰': 'England',
    '巴勒斯坦': 'Palestine'
}
